### ISSUE TITLE
ReadMe?

### ISSUE THREAD

**Issue by linusanderas** [clappr/clappr-chromecast-plugin#2]
I have hard time getting information on how to use this plugin...

**Comment by leandromoreira** [comment]
We also may add it to jsdelivery as [we do with many clappr's plugins](http://www.jsdelivr.com/?query=clappr)

**Comment by lucasdavila86** [comment]
Hi! I've searched on jsdeliver but I didn't found it. It has been taken down?

**Comment by leandromoreira** [comment]
@lucasdavila86 we still didn't upload to jsdelivr
