### ISSUE TITLE
Cannot read property '_listenId' of null

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr-chromecast-plugin#5]
Browser: All

Clappr Version: 0.2.49
clappr-chromecast-plugin version: master f5b639a

Steps to reproduce:
- open http://cdn.clappr.io/ 
- enable clappr-chromecast-plugin
- click on Run button, you'll see an error message: Cannot read property '_listenId' of null

console output:

clappr.js:9876 Uncaught TypeError: Cannot read property 'settings' of null
clappr.js:3061 [error][MediaControl] error on event mediacontrol:hide trigger - TypeError: Cannot read property 'trigger' of undefined
    at Core.onMediaControlShow (http://cdn.clappr.io/latest/clappr.js:4218:32)
    at triggerEvents (http://cdn.clappr.io/latest/clappr.js:2249:36)
    at MediaControl.trigger (http://cdn.clappr.io/latest/clappr.js:2379:10)
    at MediaControl.hide (http://cdn.clappr.io/latest/clappr.js:9707:13)
    at http://cdn.clappr.io/latest/clappr.js:9855:22

config tested with cdn.clappr.io:

var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [Chromecast]
});

player.attachTo(playerElement);

![2016-05-07 16-46-44](https://cloud.githubusercontent.com/assets/222185/15092452/51df24e0-1473-11e6-887f-34f25ca95980.png)

**Comment by sarabveer** [comment]
same error here with clappr 0.2.52

**Comment by sarabveer** [comment]
@towerz

**Comment by sarabveer** [comment]
Thanks!
